# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vue Project CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install 🔧
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm ci

      - name: Build 🔧
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm run build
